version: '3'
services:
  django:
    build:
      context: .
      dockerfile: ./dev/django.Dockerfile
    command: ["./manage.py", "runserver", "0.0.0.0:8000"]
    env_file: ./dev/.env.docker-compose
    volumes:
      - .:/opt/django
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - rabbitmq
      - minio

  celery:
    build:
      context: .
      dockerfile: ./dev/django.Dockerfile
    command: [
      "celery",
      "--app", "{{ cookiecutter.pkg_name }}.celery",
      "worker",
      "--loglevel", "INFO",
      "--without-heartbeat"
    ]
    env_file: ./dev/.env.docker-compose
    volumes:
      - .:/opt/django
    depends_on:
      - postgres
      - rabbitmq
      - minio
